name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          if [ -f uv.lock ]; then
            uv sync --frozen
          else
            uv sync
          fi

      - name: Lint
        run: uv run ruff check .

      - name: Test
        run: uv run pytest
